### ISSUE TITLE
Overheating with multiple windows

### ISSUE THREAD

**Issue by Docbroke** [vain/lariza#32] opened 2017-03-14 09:32 UTC
While opening lariza in new windows, cpu consumption increases leading to overheating. Is this related to new multiprocess architecture of lariza or a webkit2 bug ? This is seen mainly with more complex websites. This doesn't happen with chromium.

**Comment by vain** [comment] 2017-03-14 18:46
I've seen this, too. It got worse since I switched to the multi-process model. However, my experience is that lariza got a lot more stable since that switch, so I'm reluctant to switch back. I've seen very little crashes recently. And if there's a crash, it's only one tab.

This is hard to debug. All I see is some cpu load of `WebKitWebProcess` processes. Each of those processes creates cpu load of about ~5% on my machine (Intel i7-3770). This doesn't matter on my desktop workstation, but I get a lot of fan noise on my laptop. :/ I wouldn't call it "overheating", though. It's just a medium but constant cpu load.

Maybe I should write a very simple, minimal program that opens several webkit windows. If this program shows the same cpu load, it's probably a webkit issue. Might be worth posting this on the webkit mailing list. I wouldn't get my hopes up, though. These guys are already doing a pretty good job and writing a rendering engine is a tremendous task. :/ I guess optimizing for performance is not top priority at the moment.

**Comment by vain** [comment] 2017-03-24 06:43
Here you go:

https://gist.github.com/vain/ef6e61efbb9712fbb517e85f2eae540f

That's a heavily stripped down version of lariza. Run it like this:

	$ git clone https://gist.github.com/ef6e61efbb9712fbb517e85f2eae540f.git
	$ cd ef6e61efbb9712fbb517e85f2eae540f/
	$ make
	$ ./webkit-windows 

Make sure to run it from a terminal, because you need to hit ^C to properly exit it. Closing windows won't work.

It opens eight web sites and uses the multi-process model. When I run it, I can clearly see a constant background load. I don't actually use the web sites, I just have the windows open:

https://gist.githubusercontent.com/vain/69857507448d9df554d388c5846e9eef/raw/1c8a9da4057c0a14a54283b2b3dcb1ea49f41c8e/gimp-load.png

Interestingly, only *one* worker process uses the CPU. The other ones are dormant. Turns out, only *some* web sites cause background load and, ironically, in my example it's webkit.org. Comment out all the other web sites and run it again:

```C
/*client_new("http://github.com");
client_new("http://www.archlinux.de");
client_new("http://www.archlinux.org");
client_new("http://www.openbsd.org");
client_new("http://www.vim.org");
client_new("http://www.voidlinux.eu");
client_new("http://www.webkitgtk.org");*/
client_new("http://www.webkit.org");
```

Background load still there.

It also makes no difference whether I use multi-process mode or not.

Can you verify this?

**Comment by Docbroke** [comment] 2017-03-24 13:55
I too feel now that there is nothing to blame in multi-process model. For most sites there is some cpu load initially while page is loading, but after that there isn't much cpu load, unless there is autoloading at certain time intervals.
I couldn't find much load on cpu after first few seconds when testing with webkit-windows.
My initial finding of increased cpu consumption was caused by multiple windows of the same site, with autoreloading, of pages. When I checked that again firefox there was no increased cpu load as I had autoreload disabled in firefox.

Can we disable autoreloading of pages??

**Comment by vain** [comment] 2017-03-24 15:55
Autoreloading? That only happens if there is a Webkit *crash*. Or are you referring to another kind of autoreload?

Just for the record, do you see any crashes in the output of `dmesg` or, if you're using systemd, `coredumpctl`?

**Comment by Docbroke** [comment] 2017-03-24 16:27
I mean page like this, that keep reloading every few seconds ( or refreshing?)

http://www.firstpost.com/world/london-attack-why-no-amount-of-political-correctness-will-save-the-world-from-islamist-terrorism-3350526.html

**Comment by vain** [comment] 2017-03-24 16:57
That page indeed crashes my WebKit. In `dmesg`, I can see this:

    [ 3328.532407] appsrc0:src[17543]: segfault at 18 ip 00007fb3db5ee980 sp 00007fb2ecb14bc8 error 4 in libwebkit2gtk-4.0.so.37.14.12[7fb3da360000+2705000]

This triggers the page reload, yes. If you keep a tab like that open, it will crash and reload and crash and reload, over and over.

Thinking about it, autoreloading a page when there is a crash is not so useful anymore. It *was* useful when we still used the single-process model: When one tab crashed, all other tabs crashed as well; so it was useful to autoreload them. With the multi-process model, though, tabs can crash individually.

I think I'll tweak the `on_crash` handler a little bit. Probably disabling autoreload as you suggested.

(Since the web site you mentioned, firstpost.com, crashes in our minimal test program `webkit-windows` as well, I conclude that the crash itself is not a bug in lariza but in WebKit.)

**Comment by Docbroke** [comment] 2017-03-25 11:39
I couldn't find any webkit crash on that page. Additionally when I load that page in firefox, I get warning that firefox prevented page reload, with option to allow reload. I think that page triggers reloading every few seconds. Another example

www.cricbuzz.com
this site triggers reloads every few second to update cricket score.

**Comment by vain** [comment] 2017-03-25 14:49
No crash for you? Huh.

cricbuzz.com produces virtually no CPU load on my machine. I checked with Chromium's network monitor: There are indeed some HTTP requests happening to update the cricket score, but they only occur about once a minute. Very rare.

At the end of the day, this all boils down to this decision: Should there be more options in lariza, allowing the user to enable/disable certain features? Disable JavaScript, disable plugins, disable cookies, maybe disable automatic page reloading (dunno if that's possible in WebKit), and so on. My answer to that question is: Nope, use WebKit's defaults. I want things to "just work" and I want some basic adblock. That's it.

(Just for the record, the [surf](http://surf.suckless.org/) developers are about to merge their `webkit2` branch into their `master`. This means that surf will finally use WebKit2 by default. surf has a lot more options, allowing you to disable JavaScript and all that. Maybe it's worth a try.)

**Closed** 2017-03-25 16:29 UTC
