### ISSUE TITLE
input-driver [Was: Make the navigation bar able to execute scripts in `$LARIZA_PATH`]

### ISSUE THREAD

**Issue by onodera-punpun** [vain/lariza#44] opened 2017-04-27 18:47 UTC
#So I have been thinking about this kind of cool idea. The navigation bar could execute programs in `$LARIZA_PATH`, which would be something like `~/.config/lariza/navigation`.

This would allow for some cool things:
* The user could create a script called something like `s` which would search through a webpage, `p` to go to the previous webpage, etc. (though for these two `lariza` needs to be a bit more script friendly, like a fifo you could write commands to).
* Keyword based searches could just be scripts, for example the script `wi` would call `lariza https://wikipedia.org/$@`.
* Bookmark pages with a script (so calling `bm` would write the current page (or optionally an argument) to a text file.
* You could easilty write scripts to open pages with `mpv` or any other program.
* A history search script which could open the more recent result (and most similar result using something like the Levenshtein distance algorithm).
* I'm sure there are more cool posibilities.

I was thinking if the first word in a search does not match any of the files in `$LARIZA_PATH` it would pass the intput to `$LARIZA_PATH/search`. I know you dislike automatic searching if a string doesn't look like an URL, so `search` would just contain `lariza $@`, however it would also be possible to check inside `search` if the `$@` looks like an URL, if not it could run `lariza https://www.google.nl/?&q=$@`.

**Comment by vain** [comment] 2017-04-29 08:54
This reminds me a little bit of [uzbl](https://www.uzbl.org/). :)

It's an interesting idea and it would allow for a great deal of customization (for example #33, as you suggested).

Currently, we have the external handler script (see #25) which can already do some of these things. It can also do *more*, though, since it's integrated in the context menu. This means that it cannot be simply replaced like that.

Big question is, how do lariza and those scripts communicate? Note that there is no notion of "the currently active window". This means, when typing `wi foo`, lariza currently cannot know in which window to open `https://wikipedia.org/$@`. The only option is to open a new window ... meh. I'd love for this to be able to open URLs in the current window.

Maybe I'll implement this on an experimental branch and we'll see how it goes.

**Comment by vain** [comment] 2017-05-01 09:17
I've pushed an experimental implementation.

It's a little bit different than you suggested. *All* input (except for searching inside the webpage) is sent to one external script. Currently, that script is an exemplary implementation. It could do more, e.g. search for other scripts in `$LARIZA_PATH` or stuff like that. This script is also supposed to implement keyword based searches.

lariza reads the output of that script. If it says `go_uri foobarbaz`, the URI `foobarbaz` will be opened. As an example, there's also the command `go_uri_new` to open new tabs.

The current implementation doesn't integrate at all with the existing external handler. This should be improved before merging any of this. It feels very redundant.

So far, so good.

I'm not so sure about these issues:

1.  Would I make use of it? To be honest, since I wrote [browser-inputline](https://github.com/vain/bin-pub/blob/master/browser-inputline) ([see also](https://www.uninformativ.de/blog/postings/2016-06-19/0/POSTING-en.html)), I hardly use lariza's built-in keyword search anymore. :/ The big advantage of `browser-inputline` is that it works browser-independent. Yes, I do need to use browsers other than lariza.
1.  Opening the current URI with some other program is of limited use. Instead, what's really useful is opening *a link* in another program. For example, click on an image and be able to select "Open image in The GIMP". Or click on a video URI and select "Play video in mpv". That's what the external handler can do.
1.  Opening the current URI with some other program is already implemented in the external as well. It can be used to manage bookmarks, open the page's source code in Vim, and so on.
1.  There's the "context problem": How do you pass context information from lariza to an external script, e.g. page history or cookies? Maybe you need some of this information in your scripts: Maybe you need to be logged in to a web site in order to play a video with mpv, which means that you need some cookies. That's just a simple example. If you go back in history to earlier versions, you'll find that lariza used to open a terminal running `wget` in order to perform downloads. I soon realized that this often fails because of that "context problem". (Yes, the external handler suffers from this problem as well.)
1.  lariza wasn't designed to or intended to be "ubzl-like". It was intended to be a very simple browser. I feel like all you need to achieve that is a simple input box where you can enter a URI. Event the existing external handler feels a little bit like a hack.

Okay, what's the cool stuff that could be done (and that could *not* be done with the external handler or some other common script)?

1.  The C code for keyword based searches could be replaced by a Shell script or a Python script.
1.  Solve #33.

My guts tell me, that there should be a major redesign for this feature to work. Or maybe involving *external processes* is the wrong approach – see [luakit](https://github.com/luakit/luakit) which gives users a hell lot of freedom by offering a scripting framework.

**Comment by vain** [comment] 2017-05-14 16:11
For the record, I'm still working on this. It needs a little more thinking/polishing and it's not perfect, but I like that it allows for a great deal of per-user customization.

(Sorry for the slow pace lately.)

**Comment by vain** [comment] 2017-05-21 14:59
Roadmap:

-   I'll release v17.05 in a few minutes. That's going to be the state of the current master.
-   I'll rebase the branch `input-driver` and push some more commits.
-   The release after v17.05 will focus on the input driver. I'd like to refrain from adding any more features to it.

**Comment by vain** [comment] 2017-05-26 15:56
Okay, on `input-driver`, I've gone a step further. Virtually all user input is now fed through an external process. This means that you can not only control what's going on when you type some text in the input box and then hit return, but you can also manage/configure all hotkeys in that script.

Documentation is still missing. To understand what's going on, start by reading the function `input_driver()`. It runs a script called `lariza-input-driver` with some parameters. That script writes a command to its stdout to tell lariza what to do.

Still not 100% sure if I want to merge this. It's a big break. Lariza would change from "this is a C binary that does everything" to "here's a core binary and the rest is up to you and your shell scripts". Hmm, feels a bit convoluted.

Why am I doing this? To allow for much better customization without having to introduce 100 different options and code paths.

(I'm aware that this is quite different than what you initially suggested.)

**Comment by vain** [comment] 2017-06-11 14:44
Ooookay, the choice has been made. The `input-driver` branch will not be merged into `master`. Sorry.

Here's why:

-   One of lariza's main goals is simplicity. The input driver introduces a great deal of complexity, though -- both for me as a maintainer and for users (because you first have to figure out what an "input driver" is and what not).
-   The code/design on that branch is *very* inconsistent. Some events are fed to a user-supplied script, but not all events. What about events like "URI loaded"? And what about all those settings WebKit offers? Shouldn't all these things be handled by user-supplied code as well, *if you're aiming for customizability*? Seriously, lariza has never been designed for customizability. It *must* be rewritten from scratch if you want to have that.
-   Again, I just want a simple browser that works. A medium sized C program that implements a simple frontend for WebKit2. That's it. Anything else is beyond the scope of this project.

I won't delete the `input-driver` branch. If anyone out there wants to continue working on it, please do. It's free software. :-) Given the slow pace of this project (from my point of view, it's pretty much feature-complete), maintaining patches or forks should be feasible.

Again, I'm sorry to let you down.

**Closed by vain** 2017-06-11 14:44 UTC
